services:
  middletire:
    image: middletire
    build:
      context: .
      dockerfile: MiddleTire/Dockerfile

  middletire-1:
    image: middletire-1
    build:
      context: .
      dockerfile: MiddleTire/Dockerfile
      
      
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD} #Secret
      MYSQL_DATABASE: ${DATABASE_NAME} #Var
      MYSQL_USER: ${DATABASE_USER} #Var
      MYSQL_PASSWORD: ${DATABASE_PASSWORD} #Secret
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
        
        
  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - mariadb
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/${DATABASE_NAME}
      FLYWAY_USER: ${DATABASE_USER}
      FLYWAY_PASSWORD: ${DATABASE_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 5
    volumes:
      - ./db/migrations:/flyway/sql
    command: migrate
      
volumes:
  mariadb_data:
