services:
  webapi:
    build:
      context: .
      dockerfile: MiddleTire/Dockerfile
    image: ""
    depends_on:
      - mariadb
    ports:
      - "8085:8080"
  
  frontend:
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    image: ""
    ports:
      - "8080:80"