name: k6Testing.yml
on:
  push: 
    branches:
      - feat/api/ebt/k6-testing

jobs:
  test-api:
    runs-on: ubuntu-latest
    services:
      api:
        image: ghcr.io/devopseasv2025/fullstack_calculator:staging 
        ports:
          - 8085:8080  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: echo pwd 
        run: pwd

      - name: Debug Directory Structure
        run: ls -R ${{ github.workspace }}

      - name: Run k6 tests (Docker)
        run: |
          docker run --network host -v ${{ github.workspace }}/MiddleTire.Test.Loadtesting:/scripts grafana/k6 run /scripts/scripts/spike_test.js
      
