name: k6Testing.yml
on:
  push: 
    branches:
      - feat/api/ebt/k6-testing

jobs:
  test-api:
    runs-on: ubuntu-latest
    services:
      api:
        image: ghcr.io/devopseasv2025/fullstack_calculator:staging
        ports:
          - 8085:8080  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install k6
        run: |
          curl -s https://packagecloud.io/install/repositories/loadimpact/k6/script.deb.sh | sudo bash
          sudo apt install k6

      - name: Run k6 tests
        run: k6 run spike_test.js
