name: workflow.yml
on:
  push:
    branches: 
      - master
      - main
  
jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis 
      
      - name: Application Version
        id: semvar-app
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: 'true'

      - name: Install required tools
        run: |
          dotnet tool install -g dotnet-sonarscanner
          dotnet tool install -g dotnet-reportgenerator-globaltool
          dotnet tool install -g dotnet-stryker
        
      - name: Display Version
        run: echo "Generated version is ${{ steps.semvar-app.outputs.version }}"
        
      - name: Build
        run: dotnet build
        
      - name: Run unit tests
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults

      - name: Start Static Code Analysis
        run: |
          dotnet sonarscanner begin \
          /k:${{ vars.SONARQUBE_PKEY }} \
          /d:sonar.host.url=${{ vars.SONARQUBE_HOST_URL }} \
          /d:sonar.token=${{ secrets.SONARQUBE_TOKEN }} \
          /d:sonar.coverageReportPaths="coverage-report/SonarQube.xml" \
          /d:sonar.exclusions="coverage-report/**" \
          /d:sonar.qualitygate.wait=true \
          /d:sonar.qualitygate.timeout=300
      
      - name: Generate report
        run: |
          reportgenerator \
          -reports:"TestResults/**/coverage.cobertura.xml" \
          -targetdir:coverage-report \
          -reporttypes:Html, SonarQube

      - name: Complete Static Code Analysis
        run: |
          dotnet sonarscanner end \
          /d:sonar.token=${{ secrets.SONARQUBE_TOKEN }}      
      - name: Run Mutation Tests
        run: |
          dotnet stryker --break-at 40

      - name: Collect Stryker Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Stryker Report
          path: StrykerOutput