name: workflow.yml
on:
  push:
    branches: 
      - master
      - main
  
jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis 
      
      - name: Application Version
        id: semvar-app
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: 'true'

      - name: Install required tools
        run: |
          dotnet tool install -g dotnet-sonarscanner
          dotnet tool install -g dotnet-reportgenerator-globaltool
          dotnet tool install -g dotnet-stryker
          
      - name: Run unit tests
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults
      
      - name: Display Version
        run: echo "Generated version is ${{ steps.semvar-app.outputs.version }}"
        
      - name: Build
        run: dotnet build